### ISSUE TITLE
Transactions List

### ISSUE THREAD

**Issue by melanie-adler** [E-LeeSchaffer/money-manager#1]
## Value Proposition

**As a** `user`

**I want to** `browse a list of transactions`,

**so that** `I can easily track my spending and income to manage my finances`.

## Description

![Image](https://github.com/user-attachments/assets/f300345d-033b-43c8-8729-3b91f4c6b365)

## Acceptance Criteria

- The homepage displays a list of transactions distinguishing between dates.
- The transactions list is headlined with its purpose.
- Each transaction listing includes:
  - Transaction Amount
  - Transaction Category
  - Transaction Type (income or expense)
  - Transaction Date
- Income and expense transactions are visually differentiated (e.g., using different colours or icons).
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [x] Create feature branch `feature/transactions-list`.
- [x] In the `index.js`, create a header above the list named "Transactions".
- [x] Import transaction data from `transactions.json`.
- [x] Create a React component `TransactionItem` with the following details: amount, category, type (income/expense) and date.
- [x] Use conditional styling within the `TransactionItem` component to differentiate between income (green) and expense (red).
- [x] Create a React component `TransactionsList`, make sure to properly map the `TransactionItem` component.
- [x] Ensure the list of transactions is scrollable (with overflow-y: scroll).
- [x] Render on Homepage (`index.js`).

**Comment by F-Kirchhoff** [comment]
there is a small difference between description and AC / Tasks - its displayed that you distinguish between transactions from today, yesterday and different days. This is not described in AC neither in the tasks. Please make sure that these align (you can adapt the AC if you want).

**Comment by NikRoe** [comment]
LGTM
