### ISSUE TITLE
Create Transaction

### ISSUE THREAD

**Issue by melanie-adler** [E-LeeSchaffer/money-manager#2]
## Value Proposition

**As a** `user`

**I want to** `create and store new transactions`,

**so that** `I can keep track of my expenses and income effectively`.

## Description

![Image](https://github.com/user-attachments/assets/e3c5f8f7-c2b3-46f2-80fa-9c75f927176e)

## Acceptance Criteria

- A form for adding transactions is displayed at the top of the homepage.
- The form is headlined with its purpose.
- The form must include labelled fields for:
  - Transaction Amount
  - Transaction Category
  - Transaction Type
  - Transaction Date
- All fields are mandatory.
- The category is selected from the existing categories list via a dropdown menu.
- The categories dropdown must include a default option, "Please select a category", and necessitates a selection.
- The type must be selected by the user using radio buttons, allowing the choice between “Income” and “Expense”.
- The date field defaults to the current date.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new transaction is added to the top of the transactions list, and a success message is displayed.

## Tasks

- [x] Create feature branch `feature/create-transaction`.
- [x] Create a `TransactionForm` component with mandatory input fields amount (type: input), category (type: select; defaultValue: "Please select a category"), type (type: radio) and date (type: date; defaultValue: current date).
- [x] Display `TransactionForm` component on top of page.
- [x] Create `handleSubmit` function.
- [x] Within `handleSubmit` create `handleAdd` function.
- [x] Use local storage ("useLocalStorageState") with naming "newTransaction" and "setNewTransaction".
- [x] Implement success message "Transaction successfully added".
- [x] Make sure to display the new transaction at the top of the list.
- [x] Add headline "Add new transaction".
- [ ] ~~Make sure to implement proper error messaging.~~

**Comment by F-Kirchhoff** [comment]
Again, there is a misalignment between your wireframes and the AC / Tasks. There is nothing from a popup form or an additional button "add Transaction". Please simplify the wireframes (you have plenty enough time later on to move the form).

**Comment by NikRoe** [comment]
Your AC is missing the information about the success message that gets displayed after having submitted the form successfully. Please add this as a last bullet point.

**Comment by NikRoe** [comment]
👍 LGTM
