### ISSUE TITLE
Search Transactions

### ISSUE THREAD

**Issue by E-LeeSchaffer** [E-LeeSchaffer/money-manager#22]
## Value Proposition
As a `user`
I want to `search transactions names via a search bar`
In order to `quickly have access to specific transaction`.
## Description
![Image](https://github.com/user-attachments/assets/7a66f197-904f-4b6d-aefa-45c4d786cc44)

## Acceptance Criteria
- A search icon is displayed above transactions list. A search bar with focus on input field is displayed on click.
- Users can enter keywords into the search bar to search for transactions names.
- The search bar filters transaction in real time as the user types.
- The transactions list updates dynamically based on the search input.
- The search matches only transactions names.
- Previously selected filters stay selected while searching.
- If no transactions matches search input a message is displayed indicating that no transaction were found.
- The search bar can be cleared, resetting the transactions list to display all transactions.
## Tasks
- [x] Create feature branch `feature/transaction-search`.
- [x] Create `SearchBar` component above the transactions list.
- [x] Implement input handling in `SearchBar` to capture user input in real-time.
- [x] Write `filterTransactions` function to filter the transaction list based on search input.
- [x] Ensure the search works in real-time as the user types.
- [x] Display a "No matches found" message if no results match the search input.
- [x] Implement a clear/reset button to allow users to reset the search and display all transactions again.
