### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by predrag-babic** [E-LeeSchaffer/money-manager#34]
## Value Proposition
As a `user`
I want to `access other pages quickly from any section of the app`
In order to `navigate to different sections of the app quickly and conveniently`.
## Description
![Image](https://github.com/user-attachments/assets/a84a7c07-0622-4a8d-bd67-51cce7123481)
## Acceptance Criteria
- A menu icon is visible at the top corner of the app interface across all pages.
- When the icon is clicked, the menu expands to show a navigational link to the Homepage and Settings pages.
- The menu can be closed by:
Clicking the icon again
Clicking outside of the menu area (for overlay menus)
- Navigation links within the menu are clickable, redirecting the user to the respective sections.
## Tasks
- [ ] Create feature branch `feature/navigation-menu`.
- [ ] Add an menu icon to the `Header` component.
- [ ] Create a `Menu` component to display the expanded menu.
- [ ] Toggle menu visibility by adding an `isMenuOpen` state in the `Header` or `Menu` component.
- [ ] Use a background overlay or add an onClick event listener to close the menu when clicking outside.
