### ISSUE TITLE
Extended Search

### ISSUE THREAD

**Issue by melanie-adler** [E-LeeSchaffer/money-manager#39]
## Value Proposition
As a `user`
I want to `search transactions dynamically based on criteria typed directly into the search bar`
In order to `quickly find transactions by amount, category, type, or date range without navigating to separate filtering menus`.
## Description
![Image](https://github.com/user-attachments/assets/d710c2a0-294d-4194-bb8e-d01e582fd8ce)

## Acceptance Criteria
- The search bar at the top of the transactions list allows users to type in a search query.
- As the user types, the transactions list filters the results based on: amount (searching for specific amounts), category, type and date (searching for transactions on a specific date).
- tbd in TEAM: Überlegung, ob type und date in der extended Search Sinn machen.
- Search results are dynamically updated immediately as the user types in the search field.
- The clear search button resets the search input, returning the transactions list to its full, unfiltered state.
-  If there are no matches, the message "No matches found." will be shown at the top of the transaction list.
-  The search field should support partial matches (e.g., typing part of a category or date should still return results that match those parts).
## Tasks
- [ ] Create a feature branch `feature/extended-search`.
- [ ]  Implement filtering logic for the transactions list, filter by amount, category, type and date.
- [ ]  Ensure that real-time updates occur as the user types in the search field in the transaction list and account balance display.
- [ ]  Display a message "No transactions found" when no results match the search criteria.
