### ISSUE TITLE
Update Transaction

### ISSUE THREAD

**Issue by melanie-adler** [E-LeeSchaffer/money-manager#4]
## Value Proposition

**As a** `user`

**I want to** `update the details of existing transactions`,

**so that** `they reflect the most accurate and relevant information`.

## Description

![Image](https://github.com/user-attachments/assets/e58a0e2d-b981-4d1e-b628-1417e2adaf24)

## Acceptance Criteria

- Each transaction in the transactions list includes an easily accessible edit option.
- Clicking the edit option opens a form pre-filled with the transaction’s existing details for modification.
- The form allows for edits to all transaction details, including:
  - Transaction Amount
  - Transaction Category
  - Transaction Type
  - Transaction Date
- All fields are mandatory.
- The form section includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind
- Submissions with empty mandatory fields are blocked, with validation messages indicating the missing required fields
- Upon confirming the save, the updated transaction is saved and reflected in the transactions list, and a success message is displayed.

## Tasks

- [x] Create feature branch `feature/update-transaction`
- [x] In the `TransactionItem` add 2nd `Button` from existing button component.
- [x] Make sure the button leads to edit mode of the `TransactionForm` component.
- [x] In the `Button` component create `handleEdit` function and call it in the `handleSubmit` function.
- [x] Use `map` method with `id` and `useState` to update the selected transaction.
- [x] In the `TransactionForm` component make sure to the input fields are pre-filled with the already existing data from the transaction.
- [x] Display success message after updating "Transaction successfully updated".
- [x] Make sure to display updated transaction list.

**Comment by F-Kirchhoff** [comment]
there is no task describing how the update functionality is established. please update this.

**Comment by NikRoe** [comment]
Your AC is missing the information about the success message. Please add this as a bullet point.

When you want to edit an existing entry in an array, you won't be using `.filter()`. You use that array method to remove entries from an array. Which array method would be more suitable to modify an existing entry in an array?

**Comment by NikRoe** [comment]
👍  LGTM

**Comment by StephieTack** [comment]
hey together, we tried to add our most favourite word, but unfortunately it does not fit in your card. ;) 
![Bildschirmfoto 2024-10-16 um 10 12 11](https://github.com/user-attachments/assets/aca639a1-30cf-40f9-8d65-dd5df05fa7c4)
