### ISSUE TITLE
Account Balance

### ISSUE THREAD

**Issue by melanie-adler** [E-LeeSchaffer/money-manager#5]
## Value Proposition

**As a** `user`

**I want to** `see the total balance of my transactions`,

**so that** `I can quickly understand my overall financial situation`.

## Description

![Image](https://github.com/user-attachments/assets/faed2531-9d1f-4625-9c7b-f535ae20c932)

## Acceptance Criteria

- The Transaction Form is updated to a collapsable button component that can be opened to add a transaction.
- The account balance is displayed at the top of the transactions list.
- The balance includes the sum of all incomes and expenses.
- The balance updates in real-time as transactions are added, edited, or deleted.
- The account balance has a visual distinction based on its value (positive or negative).

## Tasks

- [x] Create feature branch `feature/account-balance`
- [x] Create `AccountBalance` component.
- [x] Make sure the `AccountBalance` is not shown, when adding a new transaction.
- [x] Update `TransactionForm` component with `Button` component.
- [x] Write `sumOfTransaction` function, to calculate the sum of all incomes and subtract the sum of all expenses.
- [x] Recalculate the balance whenever there is a change in the transactions list.
- [x] Use conditionally styling to handle dynamic styling (red = negative, green = positive).
- [x] Ensure that if there are no transactions, the balance is displayed as zero.

**Comment by F-Kirchhoff** [comment]
please don't use a second state for the balance, it should be derived directly from the transactions state.

**Comment by F-Kirchhoff** [comment]
please don't use a useEffect here as well.

**Comment by NikRoe** [comment]
👍

**Comment by JessicaLoers** [comment]
LGTM ✨
