### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by melanie-adler** [E-LeeSchaffer/money-manager#54]
## Value Proposition
As a `user`
I want to `view, create and edit my profile details`
In order to `keep my personal information up to date and customize my user experience`.
## Description
![Image](https://github.com/user-attachments/assets/7a0bf3c1-36fe-4cd8-982c-b21167a82a1d)

## Acceptance Criteria
- Users can access their profile by clicking on the Profile Icon in the header.
- The profile page includes sections for profile picture and full name.
- Users can view their profile details, including the profile picture ( avatar ) and full name.
- The profile page includes an edit button (using Pencil Icon), allowing users to update their details.
- Users can edit their profile picture by selecting from a set of predefined avatars and edit their name by clicking on the edit button.
- Users can enter their first and last names, each limited to 20 characters.
- A "Cancel" button is available to revert any unsaved changes.
- Upon clicking "Save," changes are saved immediately and the user will be directed to the Profile page, and a success message is displayed: “Profile successfully updated.”

- Users can select a predefined avatar from a list and add their name in the required input fields.
- A success message is displayed upon creating a profile after redirected to the profile page: “Profile successfully created.”
## Tasks
- [ ] Create feature branch `feature/user-profile`.
- [ ] Add Profile Icon to the header to navigate to the profile page.
- [ ] Create the layout for the user profile page, with sections for:
  - Profile picture ( avatar ).
  - First name and last name.
- [ ] Add an "Edit" button on the profile page that opens the form in edit mode.
- [ ] Create a dynamic form for creating or editing a profile, with the following:
  - Predefined avatars: Display a list of avatar options (grid, library ) for the user to choose from.
  - Input fields for first name and last name (both required fields).
- [ ] Validate the character limit (max 20 characters) on the first and last name input fields.
- [ ] Add Save and Cancel buttons at the bottom of the page:
  - Save Button: Saves the changes and redirects the user to the profile page.
  - Cancel Button: Reverts unsaved changes and redirects the user to the profile page.
- [ ] Allow the user to remove the existing profile picture.
- [ ] Display success messages when the profile is created or edited.
- [ ] Ensure avatar selection is visually clear:
  - Highlight the selected avatar.
  - Default to a placeholder avatar if no selection is made.

**Comment by F-Kirchhoff** [comment]
Hey!
this is already very good, I only have a few remarks regarding the initial setup of the Profile:
- You can use the same edit form for the initial setup, make sure that the default values for your user are empty strings and the placeholder avatar. Then the setup form is exactly what you get when you would press the edit button.
- When the user enters the profile page for the first time, the name fields will be empty, this should be the trigger for redirecting the user to the edit profile page. 
- The user should not be able to remove their profile picture. Just add the default avatar as one option in the avatar library, it can be an option that the user can select.
