### ISSUE TITLE
Filter Transactions

### ISSUE THREAD

**Issue by melanie-adler** [E-LeeSchaffer/money-manager#7]
## Value Proposition

**As a** `user`

**I want to** `filter transactions by category`,

**so that** `I can quickly find transactions that match my preferences and needs`.

## Description

![Image](https://github.com/user-attachments/assets/af292cda-c08b-4fde-a207-f1a01d295d34)

## Acceptance Criteria

- The transactions list includes a section with filter options.
- Filters are accessed via a dropdown that opens on click on the filter symbol.
- Users can filter transactions by category only.
- Only one category filter can be selected at a time.
- Selecting a new category filter automatically deselects the previously selected category filter.
- The applied filter is clearly displayed on the transactions list, allowing users to see which filter is currently active.
- The selected filter can be removed by clicking on it on the transactions list page or by deselecting it in the dropdown menu.
- Deselecting or changing the filter in the dropdown menu updates the transactions list in real-time.
- The transactions list updates in real-time as filters are applied or removed.
- If no transactions match the selected filter criteria, a message is displayed indicating that no transactions were found.

## Tasks

- [x] Create feature branch `feature/filter-transactions`.
- [x] Create a filter button on homepage (pages/index.js).
- [x] Create `Filter` component .
- [x] Display categories as dropdown select.
- [x] Display the updated transaction list with selected category. 
- [x] The selected category should be shown in the top of the transaction overview. 
- [x] The selected category should be displayed in the dropdown on opening and a filter is already applied.
- [x] When no transaction match the selected category display message: "No matches found".

**Comment by F-Kirchhoff** [comment]
You don't need a new page for the no matches found (the transaction list should display a message already when no transactions are found). 
There has been an error while updating the user story template. please remove the AC "Users can clear all filters with a single click", there is only one filter active at a time. Please remove the respective task as well.

**Comment by NikRoe** [comment]
Well done 👍
